files:
  - source: /languages/_en.yml
    translation: /languages/%locale%.%file_extension%
    languages_mapping:
      locale:
        ru: ru
        de: de
        id: id
        it: it
        ja: ja
        ko: ko
        pt-PT: pt
